"""version_slide_level

Revision ID: 28584ef2b733
Revises: 36960b43f00f
Create Date: 2026-06-01 12:21:10.012612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '28584ef2b733'
down_revision: Union[str, None] = '36960b43f00f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('versions', sa.Column('slide_id', sa.Uuid(), nullable=False))
    op.drop_index(op.f('ix_versions_project_id'), table_name='versions')
    op.create_index(op.f('ix_versions_slide_id'), 'versions', ['slide_id'], unique=False)
    op.drop_constraint(op.f('versions_project_id_fkey'), 'versions', type_='foreignkey')
    op.create_foreign_key(None, 'versions', 'slides', ['slide_id'], ['id'])
    op.drop_column('versions', 'project_id')
    op.drop_column('versions', 'git_commit_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('versions', sa.Column('git_commit_hash', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('versions', sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'versions', type_='foreignkey')
    op.create_foreign_key(op.f('versions_project_id_fkey'), 'versions', 'projects', ['project_id'], ['id'])
    op.drop_index(op.f('ix_versions_slide_id'), table_name='versions')
    op.create_index(op.f('ix_versions_project_id'), 'versions', ['project_id'], unique=False)
    op.drop_column('versions', 'slide_id')
    # ### end Alembic commands ###
